const http = require('http');
const jwt = require('jsonwebtoken');

const JWT_SECRET = 'earnmitra_super_secret_jwt_key_2026_secure';

function request(path, options = {}, body = null) {
  return new Promise((resolve, reject) => {
    const req = http.request(`http://localhost:3000${path}`, options, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          resolve({ status: res.statusCode, body: data ? JSON.parse(data) : null });
        } catch {
          resolve({ status: res.statusCode, raw: data });
        }
      });
    });
    req.on('error', reject);
    if (body) {
      req.setHeader('Content-Type', 'application/json');
      req.write(JSON.stringify(body));
    }
    req.end();
  });
}

async function runE2ESync() {
  console.log('====================================================');
  console.log('  EARNMITRA: 2-WAY PARTNER <-> ADMIN SYNC TEST');
  console.log('====================================================');

  // Partner Token for Partner ID 1 (P-1001)
  const partnerToken = jwt.sign(
    { id: 1, partnerId: 1, partnerCode: 'P-1001', role: 'partner', mobile: '9876543210' },
    JWT_SECRET,
    { expiresIn: '1h' }
  );
  const partnerHeaders = { 'Authorization': `Bearer ${partnerToken}` };

  // Admin Token for Super Admin
  const adminToken = jwt.sign(
    { id: 1, adminId: 1, role: 'admin', username: 'superadmin', email: 'admin@earnmitra.in' },
    JWT_SECRET,
    { expiresIn: '1h' }
  );
  const adminHeaders = { 'Authorization': `Bearer ${adminToken}` };

  // ------------------------------------------------------------------
  // STEP 1: Partner submits a new referral lead in Partner App
  // ------------------------------------------------------------------
  console.log('\n[1] Partner Mobile App: Submitting new referral lead...');
  const newLeadPayload = {
    loanType: 'Personal Loan',
    applicantName: 'Vikramaditya Verma',
    mobile: '9988776655',
    city: 'Pune',
    loanAmount: 750000,
    pan: 'ABCDE1234F',
    applicantType: 'Salaried'
  };

  const createRes = await request('/api/leads', { method: 'POST', headers: partnerHeaders }, newLeadPayload);
  if (createRes.status !== 201 && createRes.status !== 200) {
    console.error('❌ Failed to create lead from partner POV:', createRes);
    process.exit(1);
  }
  const createdLead = createRes.body;
  const leadDbId = createdLead.id || createdLead.dbId;
  const leadCode = createdLead.leadCode || createdLead.lead_code;
  console.log(`✅ Partner successfully created Lead: ${leadCode} (ID: ${leadDbId})`);

  // ------------------------------------------------------------------
  // STEP 2: Super Admin sees the lead instantly in Control Center
  // ------------------------------------------------------------------
  console.log('\n[2] Admin Control Center: Querying Master Leads pipeline...');
  const adminLeadsRes = await request(`/api/admin/leads?search=${leadCode}`, { method: 'GET', headers: adminHeaders });
  if (adminLeadsRes.status === 200 && adminLeadsRes.body.data?.length > 0) {
    const found = adminLeadsRes.body.data[0];
    console.log(`✅ Admin retrieved lead: "${found.applicant_name}" | Status: "${found.status}" | Partner: "${found.partner_name}"`);
  } else {
    console.error('❌ Admin failed to find partner lead in master pipeline:', adminLeadsRes);
    process.exit(1);
  }

  // ------------------------------------------------------------------
  // STEP 3: Admin updates lead status & stage with custom note
  // ------------------------------------------------------------------
  console.log('\n[3] Admin Control Center: Approving and Sanctioning Lead...');
  const statusUpdateRes = await request(
    `/api/admin/leads/${leadDbId}/status`,
    { method: 'PATCH', headers: adminHeaders },
    {
      status: 'Approved',
      stage: 'Sanction letter generated by HDFC Bank',
      note: 'Verified 3 years ITR, approved at 10.75% ROI with zero processing fee.'
    }
  );

  if (statusUpdateRes.status === 200 && statusUpdateRes.body.success) {
    console.log(`✅ Admin successfully transitioned Lead status to "Approved"`);
  } else {
    console.error('❌ Admin status update failed:', statusUpdateRes);
    process.exit(1);
  }

  // ------------------------------------------------------------------
  // STEP 4: Partner views updated status and stage in mobile app
  // ------------------------------------------------------------------
  console.log('\n[4] Partner Mobile App: Inspecting live application status & timeline...');
  const partnerCheckRes = await request(`/api/leads/${leadDbId}`, { method: 'GET', headers: partnerHeaders });
  if (partnerCheckRes.status === 200 && partnerCheckRes.body) {
    const pLead = partnerCheckRes.body;
    console.log(`✅ Partner sees updated status: "${pLead.status}" | Stage: "${pLead.currentStage}"`);
    console.log(`✅ Partner sees timeline events count: ${pLead.timeline?.length || 0}`);
    const latestEvent = pLead.timeline?.[pLead.timeline.length - 1];
    if (latestEvent) {
      console.log(`   Latest timeline remark: "${latestEvent.note || latestEvent.label}"`);
    }
  } else {
    console.error('❌ Partner could not see updated lead status:', partnerCheckRes);
    process.exit(1);
  }

  // ------------------------------------------------------------------
  // STEP 5: Payout Request & Approval Flow
  // ------------------------------------------------------------------
  console.log('\n[5] Payout Flow: Partner requests payout, Admin settles payout...');
  const payoutDataRes = await request('/api/payouts', { method: 'GET', headers: partnerHeaders });
  console.log(`   Partner current available balance: ₹${payoutDataRes.body?.earnings?.available || 0}`);

  // Admin views payouts
  const adminPayoutsRes = await request('/api/admin/payouts', { method: 'GET', headers: adminHeaders });
  if (adminPayoutsRes.status === 200 && adminPayoutsRes.body.data?.length > 0) {
    const samplePayout = adminPayoutsRes.body.data[0];
    console.log(`✅ Admin retrieved payout queue: Found Request #${samplePayout.reference_number || samplePayout.id}`);
    
    // Admin approves payout
    const approvePayoutRes = await request(
      `/api/admin/payouts/${samplePayout.id}`,
      { method: 'PATCH', headers: adminHeaders },
      { status: 'approved' }
    );
    if (approvePayoutRes.status === 200) {
      console.log(`✅ Admin approved Payout #${samplePayout.id}: Marked completed/paid`);
    }
  }

  // ------------------------------------------------------------------
  // STEP 6: Verify Audit Trail
  // ------------------------------------------------------------------
  console.log('\n[6] Admin Control Center: Verifying Audit Trail recorded all actions...');
  const auditRes = await request('/api/admin/audit', { method: 'GET', headers: adminHeaders });
  if (auditRes.status === 200 && auditRes.body.data?.length > 0) {
    const recentLogs = auditRes.body.data.slice(0, 3);
    console.log(`✅ System Audit Log contains ${auditRes.body.total || auditRes.body.data.length} recorded events:`);
    recentLogs.forEach(l => {
      console.log(`   - [Log #${l.id}] ${l.action} on ${l.entity_type} #${l.entity_id} at ${l.created_at}`);
    });
  }

  console.log('\n====================================================');
  console.log('🎉 2-WAY PARTNER <-> ADMIN INTERCONNECTION VERIFIED!');
  console.log('====================================================');
  process.exit(0);
}

runE2ESync().catch(err => {
  console.error('Fatal error during E2E sync verification:', err);
  process.exit(1);
});
